cart:
  env_id: CartPole-v1
  hidden_layers: 128
  replay_memory_size: 10000
  batch_size: 128
  epsilon_init: 1
  epsilon_decay: 0.9999
  epsilon_min: 0.01
  network_sync_rate: 100
  learning_rate: 0.0001
  gamma: 0.99
  epoch: 1000

tetris:
  env_id: Tetris-Nes
  hidden_layers: 256
  replay_memory_size: 10000
  batch_size: 64
  epsilon_init: 1
  epsilon_decay: 0.9999
  epsilon_min: 0.01
  network_sync_rate: 100
  learning_rate: 0.0001
  gamma: 0.95
  epoch: 500