cart:
  env_id: CartPole-v1
  hidden_layers: 512
  replay_memory_size: 10000
  batch_size: 256
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 100
  learning_rate: 0.0001
  gamma: 0.95
  epoch: 500

tetris:
  env_id: Tetris-Nes
  hidden_layers: 512
  replay_memory_size: 100000
  batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  network_sync_rate: 100
  learning_rate: 0.0001
  gamma: 0.95
  epoch: 500