tetris:
  GAMMA: 0.95
  TAU: 0.0001
  agg_height_weight: -0.2988
  bumpiness_weight: -0.2195
  env_id: Tetris-Nes
  episodes: 300
  epsilon_decay: 0.9995
  epsilon_init: 0.01
  epsilon_min: 0.01
  hidden_layers: 256
  hole_weight: -0.378
  learning_rate: 0.0002
  line_clear_weight: 0.8902
  log_dir: ''
  mini_batch_size: 64
  model_dir: ''
  replay_memory_size: 30000
  update_rate: 100
