cart:
  env_id: CartPole-v1
  hidden_layers: 512
  replay_memory_size: 100000
  batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  network_sync_rate: 10
  learning_rate: 0.0001
  discount_factor: 0.99
  epoch: 1000

tetris:
  env_id: Tetris-Nes
  hidden_layers: 512
  replay_memory_size: 100000
  batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.99995
  epsilon_min: 0.05
  network_sync_rate: 10
  learning_rate: 0.0001
  discount_factor: 0.99
  epoch: 1000